<?php

class IndexController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
//        return $this->response->setStatusCode(404, "Not Found");
//        if ($this->acl->isAllowed("Guests", "Customers", "edit")) {
//            echo "Access granted!";
//        } else {
//            echo "Access denied :(";
//        }
//        return '11';
    }
}

